version: '3'
services:
  php:
    container_name: 'webapp-php'
    build: ./docker/php/
    networks:
      - backend
    volumes:
      - ./webapp:/var/www/html
  apache:
    container_name: 'webapp-web'
    build: ./docker/apache
    depends_on:
      - php
      - mysql
    networks:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./docker/apache/conf/httpd.conf:/usr/local/apache2/conf/webapp.apache.conf
      - ./webapp:/var/www/html
  mysql:
    container_name: 'webapp-db'
    image: mysql:5.6.38
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "webapp"
    volumes:
      - mysqldata:/var/lib/mysql
      - ../:/var/www
    networks:
      - backend
    ports:
      - 3306:3306
volumes:
  mysqldata: {}

networks:
  backend:
    name: webapp-backend
    driver: "bridge"
  frontend:
    name: webapp-frontend
